### ISSUE TITLE
Feedback function not working

### ISSUE THREAD

**Issue by sptechmk** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#39] opened 2022-03-05 00:26 UTC
Hello Team while I was able to deploy the solution, I continue to see the Feedback functionality(it goes on loop for sign-in) not working in the NEO app. Is this a bug?

**Comment by Porkai-Pandian** [comment] 2022-03-07 23:58
Hi @sptechmk 

Thank you for submitting the issue, we're looking into and get back to you soon with updates.

**Comment by Porkai-Pandian** [comment] 2022-03-15 18:45
Hi @sptechmk, Feedback functionality is working fine, it's not a bug, we can discuss to troubleshoot further.

**Comment by Porkai-Pandian** [comment] 2022-04-05 19:00
HI @sptechmk,

Please let us know if you've any updates, if not we'll proceed with closing the issue.

**Closed as completed** 2022-04-25 18:45 UTC
Labels: answered
