### ISSUE TITLE
Please Sign in > Authentication Failure  

### ISSUE THREAD

**Issue by nnation** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#34] opened 2022-01-19 10:32 UTC
### While in the bot on Team, I clicked the sign in and got this message:
![image](https://user-images.githubusercontent.com/8162503/150110748-d44c2349-25fb-4798-bdb3-421aad36fcdd.png)

### On Azure Portal for the bot, I saw this
![image](https://user-images.githubusercontent.com/8162503/150111764-4b7b31d1-86e4-4e2c-9f62-3e1341fff3f8.png)

### Here is the End-to-End Transaction details
![image](https://user-images.githubusercontent.com/8162503/150112374-f1654135-858f-4650-bf7f-d6a190293013.png)

### This is the call stack:
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException:
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

**Comment by Porkai-Pandian** [comment] 2022-01-22 00:59
Hi @nnation,

Thank you for raising the query, we're looking into the issue which you've mentioned

**Comment by nnation** [comment] 2022-02-22 16:31
Hi @Porkai-Pandian, 

Any updates? This is a major roadblock for us. We are open to having a working session with you and your team to help us move forward.

**Comment by Porkai-Pandian** [comment] 2022-03-04 17:59
Hi @nnation,

Sorry for the late response, please share your email id so that we can have discussion on the same

**Comment by nnation** [comment] 2022-03-07 22:10
Hi @Porkai-Pandian, 

How do I place my email here without it being public? I wish not to be spammed by others. My Twitter handle is [@NathNation](https://twitter.com/NathNation) this is an alternative for DM

**Comment by mustafafarooq** [comment] 2022-03-09 12:59
Any solution for this found yet, I am experiencing the same issue

**Comment by Porkai-Pandian** [comment] 2022-03-09 19:35
> Hi @Porkai-Pandian,
> 
> How do I place my email here without it being public? I wish not to be spammed by others. My Twitter handle is [@NathNation](https://twitter.com/NathNation) this is an alternative for DM

Unfortunately there is no other way to contact, you can share your email, I'll copy and delete the response immediately.

**Comment by nnation** [comment] 2022-03-09 21:55
@Porkai-Pandian my email is nathaniel.nation@mcsystems.com

**Comment by Porkai-Pandian** [comment] 2022-03-09 22:02
Thanks @nnation for the details, I'll reach out to over email.

**Comment by Porkai-Pandian** [comment] 2022-03-10 17:57
Hi @nnation,

As discussed, the issue is resolved after updating "ValidDomains” section in app manifest.json file with "token.botframework.com" URL, hence closing this issue.

**Comment by Porkai-Pandian** [comment] 2022-03-10 17:57
> Any solution for this found yet, I am experiencing the same issue

Hi @mustafafarooq,

Please try the above solution, if still not working, request you to open new issue.

**Closed as completed by Porkai-Pandian** 2022-03-10 17:57 UTC
